name: adoption_ui_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  glassmorphism_ui: ^0.3.0
  image_picker: ^1.1.2
  flutter_login: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  path: ^1.9.1
  responsive_framework: ^1.5.1
  animations: ^2.0.11
  loading_gifs: ^0.3.0
  url_launcher: ^6.3.1
  firebase_database: ^11.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/products/food/
    - assets/images/products/toys/
    - assets/images/products/accessories/
    - assets/images/products/housing/
    - assets/images/products/equipment/
    - assets/images/products/grooming/
    - assets/images/crowdfunding/
    - assets/images/crowdfunding/success/
    - assets/images/crowdfunding/donors/
    - assets/images/crowdfunding/campaign1.jpg
    - assets/images/crowdfunding/campaign2.jpg
    - assets/images/crowdfunding/campaign3.jpg
    - assets/images/crowdfunding/campaign4.jpg
    - assets/images/crowdfunding/success/story1.jpg
    - assets/images/crowdfunding/success/story2.jpg
    - assets/images/crowdfunding/success/story3.jpg
    - assets/images/crowdfunding/donors/donor1.jpeg
    - assets/images/crowdfunding/donors/donor2.jpg
    - assets/service_account.json
